name: LU Testing

on: [push, pull_request]

jobs:
  luValidation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install seaborn matplotlib pyodbc
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
      - uses: actions/setup-node@v2

      - name: Install BF CLI
        run: |
          npm install @microsoft/botframework-cli
          
      - name: Run Test
        run: python ./main.py  build_test --name=EALuTest --output=./out --botname=EnterpriseAssistant --authoringkey=$Authoring_Key --region=westus --trainlu=../../../generators/generator-bot-enterprise-assistant/generators/app/templates/language-understanding/en-us/botName.en-us.lu --testlu=../tests/enterpriseassistant.tests.lu --dialog=multiLanguage --suffix=automation --authoringendpoint=https://eatest-authoring.cognitiveservices.azure.com/ --predictionkey=$Prediction_Key --predictionendpoint=https://eatest.cognitiveservices.azure.com/ --sqlserver=ealuistesting.database.windows.net --sqldatabase=LuisTestingResult --sqluser=LuisAdmin --sqlpassword=$Sql_Password
        env:
          Authoring_Key: ${{ secrets.LUISAUTHORINGKEY }}
          Prediction_Key: ${{ secrets.LUISPREDICTIONKEY }}
          Sql_Password: ${{ secrets.LuisResultSqlPassword }}
        working-directory: ./tests/lu/code